name: Erlang CI

on:
  push:
    branches: [ nhse-develop-3.2 ]
  pull_request:
    branches: [ nhse-develop-3.2 ]


jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.3.3

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: apt-get update && apt-get install -y cmake && make
      - name: Run tests
        run: apt-get update && apt-get install -y cmake libc6-dev && make check
