name: Erlang CI

on: [push, pull_request]

jobs:

  build:

    name: Build and Test on ${{matrix.os}} OTP-${{matrix.otp}} Rebar-${{matrix.rebar}}
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        otp: ['24', '26']
        rebar: ['3.22', '3.24']
        exclude:
          - otp: '24'
            os: macos-latest
          - rebar: '3.24'
            otp: '24'

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar}}

      - name: Info
        run: rebar3 --version
      - name: Compile
        run: rebar3 compile
      - name: XRef
        run: rebar3 xref
      - name: Dialyzer
        run: rebar3 dialyzer
      - name: Run tests
        run: rebar3 eunit
      - name: Build docs
        run: rebar3 edoc
      - name: Clean
        run: rebar3 clean --all
